# File: roles/common/tasks/main.yml
- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Load kernel modules for Containerd
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    create: yes
    block: |
      overlay
      br_netfilter

- name: Load kernel modules immediately
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Set system configurations for K8s networking
  blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    create: yes
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply system configurations
  command: sysctl --system

- name: Install Containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Configure Containerd
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    echo '[plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s-istioing-phoenixa-873394dda6-1066746258.us-east-1.elb.amazonaws.com"]' >> /etc/containerd/config.toml
    echo '  endpoint = ["http://k8s-istioing-phoenixa-873394dda6-1066746258.us-east-1.elb.amazonaws.com"]' >> /etc/containerd/config.toml
    systemctl restart containerd

- name: Install Prerequisites
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gpg']
    state: present
    update_cache: yes

- name: Add Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /tmp/kubernetes-apt-keyring.asc
    mode: '0644'

- name: Dearmor Kubernetes GPG key
  ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-keyring.asc
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: kubernetes

- name: Install Kubeadm, Kubelet, Kubectl
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl']
    state: present
    update_cache: yes

- name: Hold versions
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl