# File: roles/common/tasks/main.yml
- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Load kernel modules for Containerd
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    create: yes
    block: |
      overlay
      br_netfilter

- name: Load kernel modules immediately
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Set system configurations for K8s networking
  blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    create: yes
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply system configurations
  command: sysctl --system

- name: Install Containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Configure Containerd
  shell: |
    mkdir -p /etc/containerd
    containerd config default | tee /etc/containerd/config.toml
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    systemctl restart containerd

- name: Install Prerequisites
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gpg']
    state: present
    update_cache: yes

- name: Add Kubernetes GPG key
  shell: |
    mkdir -p -m 755 /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes

- name: Add Kubernetes repository
  shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

- name: Install Kubeadm, Kubelet, Kubectl
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl']
    state: present
    update_cache: yes

- name: Hold versions
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl