# File: roles/master/tasks/main.yml
- name: Initialize Kubernetes Master
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU,Mem
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu

- name: Copy Flannel manifest
  copy:
    src: ../../../k8s/kube-flannel.yml
    dest: /tmp/kube-flannel.yml

- name: Install Flannel Pod Network
  become: no
  shell: kubectl apply -f /tmp/kube-flannel.yml
  args:
    creates: /var/run/flannel/subnet.env

- name: Generate Join Command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Store join command
  add_host:
    name: "join_command_holder"
    join_command: "{{ join_command.stdout }}"