plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: tag_Role
hostnames:
  - ip-address  # <--- This was the fix (changed from public-ip-address)
  - dns-name
compose:
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'~/.ssh/phoenix-k8s-key.pem'"
  ansible_ssh_common_args: "'-o StrictHostKeyChecking=no'"