# File: site.yaml
- hosts: all
  become: yes
  roles:
    - common

- hosts: tag_Role_master
  become: yes
  roles:
    - master
    - argocd

- hosts: tag_Role_worker
  become: yes
  roles:
    - workers