# File: roles/workers/tasks/main.yml
- name: Copy the join command to server
  copy:
    src: ./join_command.sh
    dest: /tmp/join_command.sh
    mode: 0777

- name: Join the node to cluster
  shell: sh /tmp/join_command.sh
  register: joined_or_not
  ignore_errors: yes